export const inputs = {
    firstname: '',
    surname: '',
    username: '',
    email: '',
    password1: '',
    password2: '',
}
export const currentUser = {
    username: "Ngo Tan Phat",
    location: "Viet Nam",
    profilePicture: "https://example.com/images/alex.jpg",
    age: 29,
    interests: [
        "Nhiếp ảnh",
        "Du lịch",
        "Nấu ăn",
        "Đọc sách",
        "Tập thể dục",
    ],
}
export const chatroominfo = {
    username: "John Cena",
    profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
}
export const usermatch = {
    username: "Shihara",
    location: "New York, USA",
    email: "shihara@gmail.com",
    gender: 1,
    popularityRate: 80,
    profilePicture:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
    age: 25,
    liking: true,
    liked: true,
    match: true,
    score: 78,
    images: [
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.wired.com%2F2015%2F04%2Ffind-mesmerizing-creatures-web%2F&psig=AOvVaw3ZozOv4QMckn1EyqsfqI9N&ust=1736442747421000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCND7pLrP5ooDFQAAAAAdAAAAABAE",
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pexels.com%2Fsearch%2Fanimal%2F&psig=AOvVaw3ZozOv4QMckn1EyqsfqI9N&ust=1736442747421000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCND7pLrP5ooDFQAAAAAdAAAAABAJ",
    ],
    interests: [
        "Nhiếp ảnh",
        "Du lịch",
        "Nấu ăn",
        "Đọc sách",
        "Tập thể dục",
    ],
    notificationMail: true,
    notificationPush: true,
    matchID: "1",
    description: "toi ten la shihara",
    sexualOrientation: 2,
};
export const searchOptions = {
    ageRange: 24,
    popularityRange: 50,
    sort: "score",
};
export const interestNames = [
    "Nhiếp ảnh",
    "Du lịch",
    "Nấu ăn",
    "Đọc sách",
    "Tập thể dục",
    "Âm nhạc",
    "Chơi game",
    "Đi bộ đường dài",
    "Nghệ thuật",
    "Khiêu vũ",
    "Bơi lội",
    "Đạp xe",
    "Viết lách",
    "Làm vườn",
    "Thiền",
    "Phim ảnh",
    "Chạy bộ",
    "Câu cá",
    "Thủ công",
];
export const chatRoomMessages = [
    {
        author: "John Cena",
        id: "1",
        profilePicture: "https://example.com/images/alex.jpg",
        content: "Hey Phat! How’s your day going?",
    },
    {
        author: "Ngo Tan Phat",
        id: "2",
        profilePicture: "https://example.com/images/sarah.jpg",
        content: "Hi Cena! It's been great so far. What about yours?",
    },
    {
        author: "John Cena",
        id: "3",
        profilePicture: "https://example.com/images/alex.jpg",
        content: "Pretty good! Just finished a project and feeling accomplished.",
    },
    {
        author: "Ngo Tan Phat",
        id: "4",
        profilePicture: "https://example.com/images/sarah.jpg",
        content: "That’s awesome! Congrats! What’s your plan for the evening?",
    },
    {
        author: "John Cena",
        id: "5",
        profilePicture: "https://example.com/images/alex.jpg",
        content: "Thanks! Thinking of watching a movie. Any recommendations?",
    },
    {
        author: "Ngo Tan Phat",
        id: "6",
        profilePicture: "https://example.com/images/sarah.jpg",
        content: "Definitely! You should watch 'Inception'. It's a classic!",
    },
];
export const matchList = [
    {
        matchID: "1",
        read: true,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        username: "John Cena",
        content: "Hey there! How's it going?",
    },
    {
        matchID: "2",
        read: false,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        username: "sarah_connor",
        content: "I really enjoyed our last chat. Let’s plan a meetup!",
    },
    {
        matchID: "3",
        read: false,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        username: "kevin_durant",
        content: "Good morning! What’s your plan for today?",
    },
];
export const notification = [
    {
        id: 1,
        username: "john_doe",
        read: true,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        event: "message",
        date: "2025-01-08T10:00:00Z",
    },
    {
        id: 2,
        username: "jane_smith",
        read: false,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        event: "like",
        date: "2025-01-07T14:30:00Z",
    },
    {
        id: 3,
        username: "mike_tyson",
        read: false,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        event: "visit",
        date: "2025-01-07T08:15:00Z",
    },
    {
        id: 4,
        username: "anna_karenina",
        read: true,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        event: "match",
        date: "2025-01-06T20:45:00Z",
    },
    {
        id: 5,
        username: "leo_tolstoy",
        read: true,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        event: "unmatch",
        date: "2025-01-05T12:00:00Z",
    },
];
export const likedProfile = [
    {
        username: "alex_woods",
        location: "New York, USA",
        popularityRate: 87,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        age: 29,
        liking: true,
        liked: false,
        match: false,
        score: 78,
    },
    {
        username: "sarah_connor",
        location: "Los Angeles, USA",
        popularityRate: 92,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        age: 27,
        liking: false,
        liked: true,
        match: true,
        score: 95,
    },
    {
        username: "emma_brown",
        location: "London, UK",
        popularityRate: 89,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        age: 26,
        liking: true,
        liked: true,
        match: true,
        score: 85,
    },
    {
        username: "john_smith",
        location: "Sydney, Australia",
        popularityRate: 70,
        profilePicture: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Ffree-photos%2Fdog&psig=AOvVaw0-40fRcA_2lwhMKv_YFH7O&ust=1736433336502000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCNi69rKs5ooDFQAAAAAdAAAAABAE",
        age: 31,
        liking: false,
        liked: true,
        match: false,
        score: 73,
    },
];